# Generated by Django 4.1.2 on 2024-03-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Makale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("baslik", models.CharField(max_length=200)),
                ("yazarlar", models.CharField(max_length=200)),
                ("aciklamalar", models.TextField()),
                ("pdf_linki", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
