# Generated by Django 4.1.2 on 2024-03-11 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(name="makale", table="makalebilgi",),
    ]
